# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z015clg485-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Files_for_work/hardware_proj/px2_all/px2_all.cache/wt [current_project]
set_property parent.project_path E:/Files_for_work/hardware_proj/px2_all/px2_all.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/files_for_work/hardware_proj/ip_repo/px2_game_1.0 [current_project]
add_files E:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ps2_design_1.bd
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_processing_system7_0_0/ps2_design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_axi_gpio_0_0/ps2_design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_axi_gpio_0_0/ps2_design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_axi_gpio_0_0/ps2_design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_rst_processing_system7_0_100M_0/ps2_design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_rst_processing_system7_0_100M_0/ps2_design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_rst_processing_system7_0_100M_0/ps2_design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_xbar_0/ps2_design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ip/ps2_design_1_auto_pc_0/ps2_design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ps2_design_1_ooc.xdc]
set_property is_locked true [get_files E:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/ps2_design_1.bd]

read_verilog -library xil_defaultlib E:/Files_for_work/hardware_proj/px2_all/px2_all.srcs/sources_1/bd/ps2_design_1/hdl/ps2_design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ps2_design_1_wrapper -part xc7z015clg485-1
write_checkpoint -noxdef ps2_design_1_wrapper.dcp
catch { report_utilization -file ps2_design_1_wrapper_utilization_synth.rpt -pb ps2_design_1_wrapper_utilization_synth.pb }
